### ISSUE TITLE
Class 'yii\base\BaseObject' not found

### ISSUE THREAD

**Issue by akbarkhawaja** [webzop/yii2-notifications#10]
@goncaloe I suppose this is a typo since there is no clue of BaseObject class in Yii2 core. I believe it should have been yii\base\Object rather in the base Notification class. So is the case with Channel base class too which also extends from \yii\base\BaseObject

**Comment by rustamwin** [comment]
yii2 version? yii2 >= 2.0.13 yii\base\Object class deprecated
see [yii2 CHANGELOG](https://github.com/yiisoft/yii2/blob/master/framework/CHANGELOG.md)
