### ISSUE TITLE
Display filtered notification

### ISSUE THREAD

**Issue by krisanpaulino** [webzop/yii2-notifications#17]
Is it possible for me to only show filtered notification to specific user based on it's key or class?

**Comment by goncaloe** [comment]
Look at readme, you need implement the method shouldSend($channel){} to do what you intend

**Comment by krisanpaulino** [comment]
I have done it, it doesn't work. What I meant to do is to display different type of notifications in different pages for example. I don't want any account notification appears in all page on my website. Can you give an example how to do that?
