### ISSUE TITLE
Query boolean type conversion fail from integer with postgresql db

### ISSUE THREAD

**Issue by Dezinger** [webzop/yii2-notifications#7]
It 's happend when Notifications widget tries count unseen records.
`
ERROR:  operator does not exist: boolean = integer
LINE 1: ...tions" WHERE ((user_id = 0) OR (user_id = 2)) AND **("seen"=0)**
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
`

**Comment by goncaloe** [comment]
fixed
